# Generated by Django 3.2.3 on 2021-06-05 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210606_0157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skills',
            name='skill',
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='task',
        ),
    ]
