# Generated by Django 3.2.3 on 2021-06-05 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210606_0223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='person',
            name='tasks',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='css',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='html',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='js',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='text',
        ),
        migrations.AddField(
            model_name='skills',
            name='options',
            field=models.CharField(blank=True, choices=[(1, 'Встроенная кухня'), (2, 'Кухонная ниша'), (3, 'Кухня-столовая'), (4, 'Кухня-остров'), (5, 'Открытая кухня')], max_length=100),
        ),
    ]
