# Generated by Django 3.2.3 on 2021-06-05 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210606_0245'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='skills_type',
            field=models.ManyToManyField(to='app.Skills'),
        ),
        migrations.AlterField(
            model_name='skills',
            name='options',
            field=models.CharField(max_length=100),
        ),
    ]
