# Generated by Django 3.2.3 on 2021-06-06 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210606_0249'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tasks',
        ),
        migrations.RemoveField(
            model_name='person',
            name='skills_type',
        ),
        migrations.AddField(
            model_name='person',
            name='css',
            field=models.BooleanField(default=False, verbose_name='CSS'),
        ),
        migrations.AddField(
            model_name='person',
            name='django',
            field=models.BooleanField(default=False, verbose_name='Django'),
        ),
        migrations.AddField(
            model_name='person',
            name='html',
            field=models.BooleanField(default=False, verbose_name='HTML'),
        ),
        migrations.AddField(
            model_name='person',
            name='js',
            field=models.BooleanField(default=False, verbose_name='JS'),
        ),
        migrations.AddField(
            model_name='person',
            name='php',
            field=models.BooleanField(default=False, verbose_name='PHP'),
        ),
        migrations.AddField(
            model_name='person',
            name='python',
            field=models.BooleanField(default=False, verbose_name='Python'),
        ),
        migrations.AddField(
            model_name='person',
            name='react',
            field=models.BooleanField(default=False, verbose_name='React'),
        ),
        migrations.AddField(
            model_name='person',
            name='ux',
            field=models.BooleanField(default=False, verbose_name='UX/UI'),
        ),
        migrations.AddField(
            model_name='person',
            name='vue',
            field=models.BooleanField(default=False, verbose_name='VUE'),
        ),
        migrations.DeleteModel(
            name='Skills',
        ),
    ]
