# Generated by Django 3.2.3 on 2021-06-06 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210606_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='patronymic',
        ),
    ]
