# Generated by Django 3.2.3 on 2021-06-06 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_person_patronymic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='models',
            new_name='students',
        ),
    ]
