# Generated by Django 3.2.3 on 2021-06-06 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_models_person_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='analytics',
            field=models.BooleanField(default=False, verbose_name='Создание запросов для получения аналитики на основе естественного языка'),
        ),
        migrations.AlterField(
            model_name='person',
            name='platform',
            field=models.BooleanField(default=False, verbose_name='Разработка открытой платформы для мгновенного обмена сообщениями'),
        ),
        migrations.AlterField(
            model_name='person',
            name='students',
            field=models.BooleanField(default=False, verbose_name='Разработка моделей оценки студентов на основании открытых данных'),
        ),
    ]
