# Generated by Django 3.2.3 on 2021-06-06 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20210606_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='web',
            field=models.BooleanField(default=False, verbose_name='Разработка механизма сборки и исполнения кода веб-приложения в рамках архитектуры micro frontend'),
        ),
    ]
