# Generated by Django 3.2.3 on 2021-06-06 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_person_web'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='mechanism',
            field=models.BooleanField(default=False, verbose_name='Разработка механизма сборки и исполнения кода мобильных приложений в рамках микросервисной архитектуры'),
        ),
        migrations.AddField(
            model_name='person',
            name='mobile',
            field=models.BooleanField(default=False, verbose_name='Разработка мобильного приложения для автоматической фиксации участия в спортивных мероприятиях'),
        ),
    ]
